# Generated by Django 2.2 on 2023-07-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_cat', models.CharField(max_length=200)),
                ('book_desc', models.CharField(max_length=200)),
                ('book_img', models.CharField(max_length=200)),
            ],
        ),
    ]
