# Generated by Django 2.2 on 2023-07-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='book_img',
            new_name='book_rate',
        ),
    ]
