# Generated by Django 4.2.3 on 2023-07-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_item_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='book_cat',
            field=models.CharField(default='favorite', max_length=200),
        ),
    ]
