# Generated by Django 4.2.3 on 2023-07-11 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_alter_item_book_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='book_image',
        ),
    ]
