# Generated by Django 4.2.3 on 2023-07-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_remove_item_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='book_cat',
            field=models.CharField(default='favorites', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
